import { Fira_Code, Geist, Lora } from 'next/font/google'
import '@xyflow/react/dist/style.css'
import type { Metadata } from 'next'
import '@buzz8n/ui/globals.css'

const geistSans = Geist({
  variable: '--font-giest',
  subsets: ['latin'],
})

const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
})

const firaCodeMono = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${lora.variable} ${firaCodeMono.variable}`}>
        {children}
      </body>
    </html>
  )
}
