# Multi-stage build for background worker application
FROM oven/bun:1.3.1-alpine AS base

# Install system dependencies
RUN apk update
RUN apk add --no-cache libc6-compat


# Prune project
FROM base AS pruner

# Set working directory
WORKDIR /app
RUN bun install --global turbo@canary
COPY . .
RUN turbo prune @buzz8n/worker --docker

# Build stage
FROM base AS builder
RUN apk update
RUN apk add --no-cache libc6-compat

WORKDIR /app

# First install dependencies (as they change less often)
COPY --from=pruner /app/out/json/ .
RUN --mount=type=cache,target=/root/.bun/install/cache bun ci --frozen-lockfile --production


# Build the project and its dependencies
COPY --from=pruner /app/out/full/ .
# Generate the prisma client
RUN bun --filter @buzz8n/store db:generate
RUN bun --filter @buzz8n/worker build

# Remove source code from image
RUN rm -rf ./**/*/src

# Production image
FROM base AS runner
WORKDIR /app

# Create non-root user. Don't run production as root 
RUN addgroup --system --gid 1001 worker
RUN adduser --system --uid 1001 worker
USER worker


# Copy only production dependencies
COPY --from=builder --chown=worker:worker /app .


# Set environment variables
ENV NODE_ENV=production

# Health check
# HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
#   CMD curl -f http://localhost:8080/health || exit 1

# Start the application

CMD ["bun", "--filter", "@buzz8n/worker", "start"]







